-- Every content table is tenant-scoped, including unique keys and foreign keys.
CREATE TABLE settings (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id INTEGER CHECK(id=1),
  value TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON settings USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE topics (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  kind TEXT NOT NULL,
  source TEXT NOT NULL,
  published_at TEXT,
  discovered_at TEXT NOT NULL,
  score INTEGER NOT NULL,
  data TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE topics FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON topics USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE jobs (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  topic_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  status TEXT NOT NULL,
  stage TEXT NOT NULL,
  progress INTEGER NOT NULL DEFAULT 0,
  mode TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  settings TEXT NOT NULL,
  script TEXT,
  source_data TEXT,
  artifacts TEXT,
  qa TEXT,
  error TEXT,
  note TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  day TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  FOREIGN KEY(owner_id,topic_id) REFERENCES topics(owner_id,id),
  UNIQUE(owner_id,request_id)
);

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON jobs USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE job_events (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  job_id TEXT NOT NULL,
  stage TEXT NOT NULL,
  message TEXT NOT NULL,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  FOREIGN KEY(owner_id,job_id) REFERENCES jobs(owner_id,id)
);

ALTER TABLE job_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_events FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON job_events USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE reviews (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  job_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  decision TEXT NOT NULL,
  facts_checked INTEGER NOT NULL,
  rights_checked INTEGER NOT NULL,
  note TEXT NOT NULL,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  FOREIGN KEY(owner_id,job_id) REFERENCES jobs(owner_id,id)
);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON reviews USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE source_runs (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  count INTEGER NOT NULL,
  message TEXT NOT NULL,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE source_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON source_runs USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE ai_usage (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  job_id TEXT NOT NULL,
  day TEXT NOT NULL,
  kind TEXT NOT NULL,
  status TEXT NOT NULL,
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_usage FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON ai_usage USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE daily_runs (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  day TEXT,
  status TEXT NOT NULL,
  message TEXT NOT NULL,
  job_id TEXT,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,day)
);

ALTER TABLE daily_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON daily_runs USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE assets (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  filename TEXT NOT NULL,
  media_type TEXT NOT NULL,
  rights TEXT NOT NULL,
  credit TEXT NOT NULL,
  source_url TEXT NOT NULL,
  path TEXT NOT NULL,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON assets USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE article_profiles (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id INTEGER CHECK(id=1),
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE article_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_profiles FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON article_profiles USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE articles (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  request_id TEXT NOT NULL,
  status TEXT NOT NULL,
  stage TEXT NOT NULL,
  progress INTEGER NOT NULL DEFAULT 0,
  mode TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  profile TEXT NOT NULL,
  input_data TEXT NOT NULL,
  source_data TEXT NOT NULL,
  angles TEXT,
  outline TEXT,
  document TEXT,
  checks TEXT,
  error TEXT,
  note TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  UNIQUE(owner_id,request_id)
);

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON articles USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE article_versions (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  article_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  stage TEXT NOT NULL,
  payload TEXT NOT NULL,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  FOREIGN KEY(owner_id,article_id) REFERENCES articles(owner_id,id),
  UNIQUE(owner_id,article_id,version,stage)
);

ALTER TABLE article_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON article_versions USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE INDEX IF NOT EXISTS articles_updated ON articles(owner_id,updated_at);

CREATE INDEX IF NOT EXISTS jobs_day ON jobs(owner_id,day);

CREATE TABLE creation_tasks (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  request_id TEXT NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  settings TEXT NOT NULL,
  archived INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  UNIQUE(owner_id,request_id)
);

ALTER TABLE creation_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE creation_tasks FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON creation_tasks USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE task_runs (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  task_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  schedule_slot TEXT,
  action TEXT NOT NULL,
  status TEXT NOT NULL,
  stage TEXT NOT NULL,
  settings TEXT NOT NULL,
  content_id TEXT,
  error TEXT,
  reports TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  FOREIGN KEY(owner_id,task_id) REFERENCES creation_tasks(owner_id,id),
  UNIQUE(owner_id,request_id),
  UNIQUE(owner_id,task_id,schedule_slot)
);

ALTER TABLE task_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON task_runs USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE task_sources (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  task_id TEXT NOT NULL,
  topic_id TEXT NOT NULL,
  at TEXT NOT NULL,
  FOREIGN KEY(owner_id,task_id) REFERENCES creation_tasks(owner_id,id),
  FOREIGN KEY(owner_id,topic_id) REFERENCES topics(owner_id,id),
  PRIMARY KEY(owner_id,task_id,topic_id)
);

ALTER TABLE task_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_sources FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON task_sources USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE deleted_tasks (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  task_id TEXT,
  deleted_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,task_id),
  FOREIGN KEY(owner_id,task_id) REFERENCES creation_tasks(owner_id,id)
);

ALTER TABLE deleted_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE deleted_tasks FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON deleted_tasks USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE image_jobs (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  version INTEGER NOT NULL,
  status TEXT NOT NULL,
  document TEXT NOT NULL,
  settings TEXT NOT NULL,
  source_data TEXT NOT NULL,
  files TEXT,
  error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE image_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE image_jobs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON image_jobs USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE platform_meta (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  key TEXT,
  value TEXT NOT NULL,
  PRIMARY KEY(owner_id,key)
);

ALTER TABLE platform_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_meta FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON platform_meta USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE INDEX IF NOT EXISTS task_runs_task ON task_runs(owner_id,task_id,created_at);

CREATE TABLE picture_candidates (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  data TEXT NOT NULL,
  at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id)
);

ALTER TABLE picture_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE picture_candidates FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON picture_candidates USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE asset_provenance (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  asset_id TEXT,
  data TEXT NOT NULL,
  PRIMARY KEY(owner_id,asset_id),
  FOREIGN KEY(owner_id,asset_id) REFERENCES assets(owner_id,id)
);

ALTER TABLE asset_provenance ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_provenance FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON asset_provenance USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE picture_jobs (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  id TEXT,
  request_id TEXT NOT NULL,
  request TEXT NOT NULL,
  status TEXT NOT NULL,
  asset_id TEXT,
  error TEXT,
  at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,id),
  UNIQUE(owner_id,request_id)
);

ALTER TABLE picture_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE picture_jobs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON picture_jobs USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));

CREATE TABLE wechat_deliveries (
  owner_id TEXT NOT NULL DEFAULT nullif(current_setting('studio.user_id',true),'') REFERENCES app_users(id),
  run_id TEXT,
  article_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  mode TEXT NOT NULL,
  status TEXT NOT NULL,
  data TEXT NOT NULL,
  error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id,run_id),
  FOREIGN KEY(owner_id,run_id) REFERENCES task_runs(owner_id,id)
);

ALTER TABLE wechat_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE wechat_deliveries FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_access ON wechat_deliveries USING (owner_id = current_setting('studio.user_id',true)) WITH CHECK (owner_id = current_setting('studio.user_id',true));
