import CenteredModal from './CenteredModal';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,LoaderCircle,Mail,Settings2,ShieldCheck,Users,X} from 'lucide-react';
import {api,dateText,send} from './api';
import {useAuth,type User} from './Auth';
import {useNotifications} from './Notifications';
import {useConfirmation} from './Confirmation';

interface MailConfig {host:string;port:number;security:'ssl'|'starttls';username:string;password?:string;sender:string;sender_name:string;password_configured?:boolean;ready?:boolean}
const defaultMail:MailConfig={host:'',port:465,security:'ssl',username:'',password:'',sender:'',sender_name:'知序创作平台'};
interface Event {id:number;actor_email:string;target_id:string;action:string;created_at:string}
export default function AdminPage(){
  const {user}=useAuth(),{error,success}=useNotifications(),confirm=useConfirmation();
  const [users,setUsers]=useState<User[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[query,setQuery]=useState(''),[search,setSearch]=useState('');
  const [open,setOpen]=useState(false),[mail,setMail]=useState<MailConfig>(defaultMail),[enabled,setEnabled]=useState(false),[events,setEvents]=useState<Event[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  const load=async()=>{const [u,s,e]=await Promise.all([api<{items:User[];total:number}>(`/admin/users?page=${page}&query=${encodeURIComponent(search)}`),api<{registration_open:boolean;smtp:MailConfig}>('/admin/settings'),api<Event[]>('/admin/events')]);setUsers(u.items);setTotal(u.total);setEnabled(s.registration_open);setMail({...defaultMail,...s.smtp,password:''});setEvents(e);};
  useEffect(()=>{setLoading(true);load().catch(e=>error(e.message)).finally(()=>setLoading(false));},[page,search]);
  const update=async(u:User,changes:{role:User['role'];status:User['status']})=>{if(!await confirm({title:changes.status==='disabled'?'停用这个用户？':'更新用户权限？',message:changes.status==='disabled'?'该用户会立即退出登录，新任务和定时执行将停止启动。已经开始的任务可能继续完成，作品会保留。':'用户需要重新登录，原有作品和配置会保留。',confirmLabel:'确认更新'}))return;setBusy(true);try{await api('/admin/users/'+u.id,send('PUT',changes));await load();success('用户设置已更新。');}catch(e){error((e as Error).message);}finally{setBusy(false);}};
  return <section className="admin-page"><div className="platform-heading"><div><h1>管理中心</h1><p>管理平台成员、注册方式与邮件服务。</p></div><button className="ss-btn" onClick={()=>setOpen(true)}><Settings2/>平台设置</button></div><div className="admin-summary"><span><Users/><b>{total}</b> 位用户{search?'符合搜索条件':''}</span><span><ShieldCheck/>{enabled?'邮箱验证注册已开放':'注册已关闭'}</span><span><Mail/>{mail.ready?'邮件服务已配置':'待配置邮件服务'}</span></div>
    {!mail.ready&&<div className="auth-note">配置 SMTP 后，新用户才能接收注册验证码，已有用户也可以通过邮件找回密码。<button className="auth-text" onClick={()=>setOpen(true)}>去配置</button></div>}
    <form className="admin-search" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(query);}}><input aria-label="搜索用户" placeholder="搜索邮箱或昵称" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/><button className="ss-btn">搜索</button></form>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>用户</th><th>权限</th><th>状态</th><th>加入时间</th><th>操作</th></tr></thead><tbody>{loading?<tr><td colSpan={5}><LoaderCircle className="spin"/> 正在读取用户…</td></tr>:users.map(u=><tr key={u.id}><td><strong>{u.display_name}</strong><small>{u.email}</small>{!u.email_verified&&<small>初始化管理员 · 邮箱尚未验证</small>}</td><td>{u.role==='admin'?'管理员':'创作者'}</td><td><span className={'ss-badge '+(u.status==='disabled'?'admin-disabled':'')}>{u.status==='active'?'正常':'已停用'}</span></td><td>{dateText(u.created_at)}</td><td>{u.id===user.id?<span className="inline-hint">当前账号</span>:<div className="admin-actions"><button className="ss-btn" disabled={busy} onClick={()=>update(u,{role:u.role==='admin'?'user':'admin',status:u.status})}>{u.role==='admin'?'设为创作者':'设为管理员'}</button><button className="ss-btn" disabled={busy} onClick={()=>update(u,{role:u.role,status:u.status==='active'?'disabled':'active'})}>{u.status==='active'?'停用':'启用'}</button></div>}</td></tr>)}</tbody></table></div><div className="admin-pagination"><button className="icon-button" aria-label="上一页用户" disabled={page===1} onClick={()=>setPage(x=>x-1)}><ChevronLeft/></button><span>第 {page} 页</span><button className="icon-button" aria-label="下一页用户" disabled={page*30>=total} onClick={()=>setPage(x=>x+1)}><ChevronRight/></button></div>
    <details className="admin-audit"><summary>最近管理操作</summary>{events.map(e=><div key={e.id}><span>{e.actor_email||'系统'}</span><span>{e.action==='bootstrap'?'初始化管理员':e.action==='smtp:update'?'修改邮件服务':e.action.startsWith('registration:')?'调整注册开关':e.action.startsWith('user:')?'调整用户权限或状态':'管理操作'}{e.target_id&&e.target_id!==user.id?' · '+(users.find(u=>u.id===e.target_id)?.email||e.target_id):''}</span><small>{dateText(e.created_at)}</small></div>)}</details>
    {open&&<CenteredModal titleId="admin-settings-title" onClose={()=>setOpen(false)} busy={busy} className="admin-settings"><button className="icon-button auth-close" aria-label="关闭平台设置" disabled={busy} onClick={()=>setOpen(false)}><X/></button><h2 id="admin-settings-title">平台设置</h2><label className="check-line admin-registration"><input type="checkbox" checked={enabled} disabled={busy} onChange={async e=>{const next=e.target.checked;setBusy(true);try{await api('/admin/registration',send('PUT',{enabled:next}));setEnabled(next);success(next?'邮箱验证注册已开放。':'注册已关闭。');}catch(e){error((e as Error).message);}finally{setBusy(false);}}}/>允许新用户通过邮箱验证注册</label><h3>验证码邮件</h3><p>使用邮箱服务商提供的 SMTP 地址和授权码，支持加密连接。</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{setMail({...defaultMail,...await api<MailConfig>('/admin/smtp',send('PUT',mail)),password:''});success('邮件服务配置已保存。');}catch(e){error((e as Error).message);}finally{setBusy(false);}}}><fieldset disabled={busy}><div className="admin-form-grid"><label className="field">SMTP 地址<input required value={mail.host} placeholder="例如 smtp.qq.com" onChange={e=>setMail({...mail,host:e.target.value})}/></label><label className="field">端口<input type="number" min={1} max={65535} required value={mail.port} onChange={e=>setMail({...mail,port:Number(e.target.value)})}/></label><label className="field">连接加密<select value={mail.security} onChange={e=>setMail({...mail,security:e.target.value as MailConfig['security']})}><option value="ssl">SSL / TLS</option><option value="starttls">STARTTLS</option></select></label><label className="field">SMTP 账号<input autoComplete="off" value={mail.username} onChange={e=>setMail({...mail,username:e.target.value})}/></label><label className="field">密码 / 邮箱授权码<input type="password" autoComplete="new-password" value={mail.password||''} placeholder={mail.password_configured?'已保存，留空保留':'填写服务商授权码'} onChange={e=>setMail({...mail,password:e.target.value})}/></label><label className="field">发件邮箱<input required type="email" value={mail.sender} onChange={e=>setMail({...mail,sender:e.target.value})}/></label><label className="field">发件人名称<input required maxLength={60} value={mail.sender_name} onChange={e=>setMail({...mail,sender_name:e.target.value})}/></label></div><div className="admin-actions"><button className="ss-btn ss-primary">保存邮件配置</button><button className="ss-btn" type="button" disabled={!mail.ready} onClick={async()=>{setBusy(true);try{const r=await api<{message:string}>('/admin/smtp/test',send('POST'));success(r.message);}catch(e){error((e as Error).message);}finally{setBusy(false);}}}>发送测试邮件给我</button></div></fieldset></form></CenteredModal>}
  </section>;
}
