import type {CollectedItem,CollectionReport,Topic} from './types';

export const topicItem=(t:Topic):CollectedItem=>({topic_id:t.id,title:t.title,url:t.sources[0]?.url||'',summary:t.sources[0]?.text?.slice(0,600)||t.angle,full_text:!!t.page_data?.full_text});
const sourceDate=(value?:string|null)=>value&&!Number.isNaN(Date.parse(value))?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'日期不明';

export default function CollectedSources({reports=[],topics=[],used,title='本次采集资料'}:{reports?:CollectionReport[];topics?:Topic[];used?:string[];title?:string}){
  const legacy=reports.some(r=>r.count>0&&!r.items);
  const reported=reports.flatMap(r=>r.items||[]);
  const candidates=legacy?topics.filter(t=>reports.some(r=>r.count>0&&!r.items&&r.source===t.source)).map(topicItem):[];
  const items=[...new Map((reports.length?[...reported,...candidates]:topics.filter(t=>!used||used.includes(t.id)).map(topicItem)).map(t=>[t.topic_id,t])).values()];
  if(!reports.length&&!items.length)return null;
  return <details className="collected-sources" open><summary>{title} <span className="ss-badge">{items.length} 篇</span>{used&&<small>本次采用 {items.filter(i=>used.includes(i.topic_id)).length} 篇</small>}</summary>
    {legacy&&<p className="inline-hint">早期执行未保存完整采集清单，以下补充展示该任务已保存的同来源资料；“本次采用”依据创作记录标记。</p>}
    {reports.map((r,i)=>r.query&&<div className="search-result-summary" key={i}><strong>检索词：{r.query}</strong><span>搜索候选 {r.candidate_count||0} 条 · 排除 {r.excluded?.length||0} 条 · 保留 {r.count} 篇{(r.unprocessed_count||0)>0&&` · 未完成筛选或采集 ${r.unprocessed_count} 条`}{r.pages_searched!==undefined&&` · 已检索 ${r.pages_searched} 页`}</span>{r.date_filter?<><span className="collection-date-filter">本次筛选：{r.date_filter.max_age_days?`近 ${r.date_filter.max_age_days} 天 · ${sourceDate(r.date_filter.from)} 至 ${sourceDate(r.date_filter.to)}（北京时间）`:'不限发布时间'}</span>{r.date_excluded_count!==undefined&&<small>时间不符或日期不明 {r.date_excluded_count} 条 · 主题不符 {r.relevance_excluded_count||0} 条{(r.deferred_count||0)>0&&` · 通过筛选但超出本次采集上限 ${r.deferred_count} 条`}</small>}</>:<small>此记录未保存当时的时间筛选条件，请重新采集以核对当前配置。</small>}{r.collected_at&&<small>采集于 {sourceDate(r.collected_at)}（北京时间） · 修改配置后需重新采集</small>}{r.search_note&&<small>{r.search_note}</small>}{r.heat_note&&<small>{r.heat_note}</small>}</div>)}
    {reports.length>0&&<details className="collection-log"><summary>采集与筛选说明 · {reports.length} 个来源</summary>{reports.map((r,i)=><div key={i}><p className={r.status==='error'?'source-error':''}>{r.source}：{r.message}</p>{r.search_url&&<a href={r.search_url} target="_blank" rel="noreferrer">查看搜索页面 ↗</a>}{!!r.excluded?.length&&<details><summary>已排除 {r.excluded.length} 条不符合要求的结果</summary>{r.excluded.map((item,j)=><div className="excluded-source" key={j}><strong>{item.title}</strong><small>{item.publisher&&`${item.publisher} · `}发布时间：{sourceDate(item.published_at)}{item.published_at&&'（北京时间）'}</small><span>{item.reason}</span>{item.url&&<a href={item.url} target="_blank" rel="noreferrer">查看该候选文章 ↗</a>}</div>)}</details>}</div>)}</details>}
    <div className="collected-list">{items.map((item,i)=><article className="collected-item" key={item.topic_id}><span className="source-number">{String(i+1).padStart(2,'0')}</span><div><div className="collected-title"><strong>{item.title}</strong>{used&&<span className={'ss-badge '+(used.includes(item.topic_id)?'ss-green':'')}>{used.includes(item.topic_id)?'本次采用':legacy?'同来源资料':'未采用'}</span>}</div><small>{item.platform==='wechat'?'公众号 · ':''}{item.publisher||''}{item.published_at&&' · '+item.published_at.slice(0,10)} · {item.full_text?'正文快照':'资料摘要'}{item.url&&' · '+new URL(item.url).hostname}</small>{item.platform==='wechat'&&<small className="source-heat">阅读量未提供 · 热度未核验</small>}<p>{item.summary}</p>{item.relevance_reason&&<div className="source-relevance">入选原因：{item.relevance_reason}</div>}{item.access_note&&!item.full_text&&<div className="source-access">{item.access_note}</div>}{item.url&&<a href={item.url} target="_blank" rel="noreferrer">{item.platform==='wechat'&&!item.full_text?'打开公众号文章入口 ↗':'打开原文 ↗'}</a>}</div></article>)}</div>
    {!items.length&&<p className="inline-hint">此记录暂无可展示的文章，查看采集说明了解原因。</p>}
  </details>;
}
