import {ImagePlus} from 'lucide-react';
import {AssetUpload} from './MaterialsPage';
import type {Asset,IllustrationSettings,SavedModel} from './types';
import './pictures.css';
import PictureSources from './PictureSources';

export const defaultIllustration:IllustrationSettings={enabled:false,mode:'smart',web_source:'licensed',cover:true,count:3,style:'自然、简洁，与文章内容一致，不添加文字或水印',model_id:'',ratio:'landscape',failure:'skip',asset_ids:[]};
export default function IllustrationConfiguration({value,models,assets,onChange,onAsset,onError}:{value?:IllustrationSettings;models:SavedModel[];assets:Asset[];onChange:(s:IllustrationSettings)=>void;onAsset:(a:Asset)=>void;onError:(s:string)=>void}){
  const s={...defaultIllustration,...value},patch=(v:Partial<IllustrationSettings>)=>onChange({...s,...v});
  return <section className={'connection-card illustration-config'+(s.enabled?' is-enabled':'')} aria-label="文章配图配置">
    <div className="illustration-heading"><span className="picture-symbol"><ImagePlus/></span><div><h2>文章配图</h2><p>{s.enabled?'按以下配置生成图文，编辑时仍可逐张修改。':'默认纯文字，需要时再开启。'}</p></div><label className="picture-switch"><input type="checkbox" aria-label="启用智能配图" checked={s.enabled} onChange={e=>patch({enabled:e.target.checked})}/><span/>{s.enabled?'已开启智能配图':'启用智能配图'}</label></div>
    {s.enabled&&<div className="illustration-options"><div className="picture-mode-options">{([['manual','已有素材','使用选中的本地图片'],['web','联网找图','按主体匹配相关实景图'],['ai','AI 生成','按正文内容创作配图'],['smart','智能混合','实景找图，概念用 AI']] as const).map(([mode,name,description])=><button type="button" key={mode} aria-pressed={s.mode===mode} onClick={()=>patch({mode})}><strong>{name}</strong><small>{description}</small></button>)}</div>
    <div className="field-pair"><label className="field">正文配图数量<select value={s.count} onChange={e=>patch({count:Number(e.target.value)})}>{[0,1,2,3,4,5,6].map(n=><option key={n} value={n}>{n===0?'不配正文图':`最多 ${n} 张`}</option>)}</select></label><label className="check-line"><input type="checkbox" checked={s.cover} onChange={e=>patch({cover:e.target.checked})}/>同时配置封面</label></div>
    {s.mode==='manual'?<><p className="inline-hint">按所选素材顺序分配：封面在前，正文在后。数量不足时其余位置留空。</p><div className="article-source-picker">{assets.filter(a=>a.media_type.startsWith('image/')).map(a=><label key={a.id}><input type="checkbox" checked={s.asset_ids.includes(a.id)} disabled={s.asset_ids.length>=20&&!s.asset_ids.includes(a.id)} onChange={()=>patch({asset_ids:s.asset_ids.includes(a.id)?s.asset_ids.filter(id=>id!==a.id):[...s.asset_ids,a.id]})}/><span>{s.asset_ids.includes(a.id)&&`${s.asset_ids.indexOf(a.id)+1}. `}{a.filename}<small>{a.credit||a.rights}</small></span></label>)}</div><AssetUpload onError={onError} onUploaded={a=>{onAsset(a);if(a.media_type.startsWith('image/')&&s.asset_ids.length<20)patch({asset_ids:[...s.asset_ids,a.id]});}}/></>:<>
    <div className="field-pair"><label className="field">生成图片比例<select value={s.ratio} onChange={e=>patch({ratio:e.target.value as IllustrationSettings['ratio']})}><option value="landscape">横版 3:2</option><option value="square">方形 1:1</option><option value="portrait">竖版 2:3</option></select></label><label className="field">配图失败时<select value={s.failure} onChange={e=>patch({failure:e.target.value as IllustrationSettings['failure']})}><option value="skip">跳过缺图，继续创作</option><option value="pause">暂停，保留已完成内容</option>{s.mode!=='ai'&&<option value="ai">找不到相关图片时改用 AI</option>}</select></label></div>
    {(s.mode==='ai'||s.mode==='smart'||s.failure==='ai')&&<><label className="field">配图使用的图片模型<select value={s.model_id} onChange={e=>patch({model_id:e.target.value})}><option value="">请选择图片模型</option>{models.filter(m=>m.protocol==='images').map(m=><option key={m.id} value={m.id}>{m.name} · {m.ready?m.model:'待配置'}</option>)}</select></label><a className="text-button" href="#models">到“我的模型”添加图片模型 ↗</a><label className="field">配图风格<textarea rows={2} maxLength={600} value={s.style} onChange={e=>patch({style:e.target.value})} placeholder="例如：自然光、纪实感、暖色调，不添加文字"/></label></>}
    {s.mode!=='ai'&&<><PictureSources value={s.web_sources?.length?s.web_sources:s.web_source==='web'?['bing']:['commons','openverse']} onChange={v=>{if(v.length)patch({web_sources:v});}}/><p className="inline-hint">至少选择一个来源，自动执行时合并所选网站的结果。开放图库提供授权信息，其他网络图片的使用条件以来源页面为准；找不到相关图片时按失败策略处理。</p></>}
    </>}
    <p className="picture-policy-note">每次生成正文后执行本配置。已有图片和锁定位置保留；关闭后，后续创作不再自动找图或生成图片。</p></div>}
  </section>;
}
