import {useEffect,useState} from 'react';
import {Upload} from 'lucide-react';
import {api,dateText} from './api';
import {SourceSettings} from './ConnectionSettings';
import type {Asset,Settings,Topic} from './types';

export function AssetUpload({onUploaded,onError}:{onUploaded:(a:Asset)=>void;onError:(s:string)=>void}){
  const [file,setFile]=useState<File|null>(null),[rights,setRights]=useState(''),[credit,setCredit]=useState(''),[busy,setBusy]=useState(false);
  const upload=async()=>{if(!file)return;setBusy(true);try{const form=new FormData();form.set('file',file);form.set('rights',rights);form.set('credit',credit);onUploaded(await api<Asset>('/assets',{method:'POST',body:form}));setFile(null);}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  return <details className="asset-upload"><summary>上传图片 / 视频素材</summary><fieldset className="article-fields" disabled={busy}><label className="field">选择文件<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="field">使用权说明<input value={rights} onChange={e=>setRights(e.target.value)} placeholder="例如：本人拍摄，可用于本次创作"/></label><label className="field">署名<input value={credit} onChange={e=>setCredit(e.target.value)}/></label><button className="ss-btn" disabled={!file||rights.trim().length<4} onClick={upload}><Upload/>{busy?'上传中…':'上传素材'}</button></fieldset></details>;
}
export default function MaterialsPage({settings,topics,onSaved,onRefresh,onError,onNotice}:{settings:Settings;topics:Topic[];onSaved:(s:Settings)=>void;onRefresh:()=>Promise<unknown>;onError:(s:string)=>void;onNotice:(s:string)=>void}){
  const [assets,setAssets]=useState<Asset[]>([]),[filter,setFilter]=useState('');useEffect(()=>{api<Asset[]>('/assets').then(setAssets).catch(e=>onError(e.message));},[]);
  return <section><div className="platform-heading"><div><span className="fn-label">MATERIAL LIBRARY</span><h1>素材库</h1><p>收集公开网页与创作素材，在不同任务中选择使用。任务也可以配置自己的专属采集来源。</p></div></div><SourceSettings settings={settings} onSaved={onSaved} onCollected={onRefresh}/><div className="materials-grid"><section className="connection-card"><div className="section-title"><h2>已收集资料</h2><span className="ss-badge">{topics.length}</span></div><label className="field">搜索资料<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="标题关键词"/></label><div className="library-topics">{topics.filter(t=>t.title.includes(filter)).map(t=><details key={t.id}><summary>{t.title}<small>{t.source} · {dateText(t.discovered_at)}</small></summary><p className="captured-text">{t.sources[0]?.text||t.angle}</p>{t.sources.filter(s=>s.url).map(s=><a key={s.id} href={s.url} target="_blank" rel="noreferrer">查看原文 ↗</a>)}</details>)}{!topics.length&&<p className="inline-hint">添加网址并采集，或使用正文导入。</p>}</div></section><section className="connection-card"><div className="section-title"><h2>图片与视频</h2><span className="ss-badge">{assets.length}</span></div><AssetUpload onError={onError} onUploaded={a=>{setAssets(v=>[a,...v]);onNotice('素材已保存，可在任务中选择。');}}/><div className="asset-library">{assets.map(a=><figure key={a.id}>{a.media_type.startsWith('image/')?<img loading="lazy" src={`/api/assets/${a.id}/file`} alt={a.filename}/>:<video controls preload="metadata" src={`/api/assets/${a.id}/file`}/>}<figcaption>{a.filename}<small>{a.rights}{a.credit?' · '+a.credit:''}</small></figcaption></figure>)}</div></section></div></section>;
}
